- name: Tap Railwaycat\'s emacs port
  homebrew_tap: tap=railwaycat/emacsmacport state=present

- name: Install Railwaycat\'s emacs port
  homebrew_cask: name=emacs-mac state=present

- name: Install regular emacs for in Terminal
  homebrew: name=emacs install_options=HEAD,cocoa,srgb,with-gnutls

- name: Install Applications
  homebrew_cask: name={{ item }} state=installed
  with_items: